version: "3.9"
services:
  firstApp:
    container_name: micro-fe-2
    image: micro-fe-2
    restart: "no"
    build:
      context: ./
      dockerfile: ./docker/dockerfile.dev
    volumes:
      - .:/app
    ports:
      - 8082:8082
    environment:
      - PORT=8082
    networks:
      - frontend-2
    tty: true

networks:
  frontend-2:
    external: true
